spring:
  application:
    name: animal-rescue-backend
  main:
    banner-mode: off
  info:
    build:
      location: classpath:META-INF/cnb-meta.properties
  logging:
    pattern:
      console: #Include namespace and cluster?
  server:
    port: 8080
    shutdown: graceful
  management:
    endpoint:
      health:
        show-details: when_authorized
    endpoints:
      web:
        exposure:
          include:
          - "info"
          - "health"
          - "httptrace"
          - "threaddump"
          - "loggers"
          - "metrics"
          - "heapdump"
          - "configprops"
          - "prometheus "
          - "conditions" # When profile == dev
          - "configprops" # When profile == dev
          - "env" # When profile == dev
          - "beans" # When profile == dev
