apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: clouddns-dns01-solver-svc-acct
  type: Opaque
  files:
  - ../secret/credentials.json
  namespace: external-dns
generatorOptions:
  disableNameSuffixHash: true
